# Generated by Django 3.2.4 on 2021-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='typeof',
            field=models.CharField(choices=[('tech', 'Technology'), ('code', 'coding'), ('termux', 'Technology')], default='code', max_length=30),
        ),
    ]
