# Generated by Django 3.2.4 on 2021-06-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blogpost_typeof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='typeof',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='code', max_length=30),
        ),
    ]
