# Generated by Django 3.2.4 on 2021-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blogpost_typeof'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
